sources:
  - name: Trends 
    table: TrendBenchmarks
    daysToLoad: 14
    stdevCount: 7
    daysToSkip: 1
    rules:
      - include: .
      - include: Mvc
        labels: 
          - area-mvc
        owners:
          - sebastienros
      - exclude: ulib
    regressions:
      probes: 
        - path: results[0].result
      labels: 
        - Perf
        - perf-regression
      owners:
        - DrewScoggins
      template: rps
      healthCheck: true

  #- name: EFCoreCrank
  #  table: EFCoreCrank
  #  daysToLoad: 30
  #  stdevCount: 7
  #  daysToSkip: 4
  #  rules:
  #    - include: AddDataVariations.Add
  #      labels: 
  #        - area-efcore
  #      owners:
  #        - sebastienros
  #  regressions:
  #    labels: 
  #      - Perf
  #      - perf-regression
  #    owners:
  #      - sebastienros
  #    template: rps
  #    healthCheck: true

templates:
  rps: "A performance regression has been detected for the following scenarios: \n\n
      | Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation | StDev | \n
      | -------- | ----------- | ---- | ------- | ------- | ------ | --------- | ----- | \n
      {% for regression in Regressions %}
      {% assign r = regression.CurrentResult %}
      {% assign p = regression.PreviousResult %}
      {% assign result = r.Data.results[0].result %}
      {% assign prevResult = p.Data.results[0].result %}
      {% assign change = regression.Change | divided_by: prevResult | times: 100 | round: 2 %}
      {% assign deviation = regression.Change | divided_by: regression.StandardDeviation | round: 2 %}
      | {{r.Scenario}} {% if regression.HasRecovered %}[Fixed]{% endif %} | {{r.Description}} | {{r.DateTimeUtc | format_date: 'G'}} | {{prevResult | format_number: 'N0' }} | {{result | format_number: 'N0' }} | {{change | format_number: 'N2'}} % ({{regression.Change | format_number: 'N0'}}) | {{deviation | format_number: 'N2'}} Ïƒ | {{ regression.StandardDeviation | format_number: 'N2'}} | \n
      {% endfor %}
      "